version: "3.7"

services:
  wordpress:
    depends_on:
      - db
    image: wordpress:5.6
    restart: unless-stopped
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./disable_plugins.sh:/usr/local/bin/disable_plugins.sh
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
      DISABLED_PLUGINS: ${DISABLED_PLUGINS}

  db:
    image: mysql:5.7
    volumes:
      # uncomment if you want mysql to be persistent
      # - mysql:/var/lib/mysql
      - ./import/${DB_BACKUP_FILE}:/docker-entrypoint-initdb.d/${DB_BACKUP_FILE}
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
# uncomment if you want mysql to be persistent
# volumes:
#   mysql:
